### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by fatlazycat** [halirutan/IntelliJ-Key-Promoter#1]
Sorry, when I look in the list of plugins I only see the one from 5 years ago.

Am I meant to add a new repo ?

Thanks

**Comment by halirutan** [comment]
@fatlazycat The "Key Promoter X" plugin is still *under review* by the Jetbrains team. Until this is finished, the plugin won't appear in the official list if you "browse plugins" inside IDEA. You can still simply install it:

1. Download the file `Key-Promoter-X...zip` from the  [latest release](https://github.com/halirutan/IntelliJ-Key-Promoter/releases)
2. In IDEA, go to Settings -> Plugins -> Install from disk (make sure you have uninstalled any former versions of the Key Promoter)

**Comment by fatlazycat** [comment]
Ah thanks
