### ISSUE TITLE
Incorrect promotion: Annotate

### ISSUE THREAD

**Issue by hurricup** [halirutan/IntelliJ-Key-Promoter#11]
Invoking `Annotate` on the editor's gutter causes following promotion (on win, actual IU)

![image](https://user-images.githubusercontent.com/2811330/29118635-738e418c-7d0b-11e7-9678-41681dda285d.png)

Clicking `Alt-N` causes `Navigate` menu opening

**Comment by halirutan** [comment]
Clearly the wrong suggestions. Unfortunately, when you right-click the gutter and select `Annotate` I cannot collect the correct information. First of all, each VCS (Git, SVN, Mercurial) has its own `Annotate` so there wouldn't even be one shortcut you can assign.

When I debug this, then the "place" where your mouse-click happens is even "unknown" to IDEA and there is no shortcut assigned to the action. What I do in such rare cases is to use the mnemonic which here is `N` but this is unfortunately not enough information. I have to turn the shortcut tip for this off.

You have the following options (tested on Linux) to get this action:

1. With `Alt` pressed type `S` then `G` (if you use Git) then `N`
2. `Alt +BackQuote` to open the VCS popup, then `5` (that should be the preferred way)
3. `Ctrl+Shift+A`, type `Annotate` and use the one with the one with the On/Off switch
