### ISSUE TITLE
Key Promoter X is not showing popups with shortcuts

### ISSUE THREAD

**Issue by pedrofsn** [halirutan/IntelliJ-Key-Promoter#12]
This start happens after Android Studio receive update for version 3.0.

**Comment by halirutan** [comment]
Can you provide information about the operating system you are using and check if there is something in the `idea.log`?

**Comment by zach007** [comment]
i got the same issus ~ it's fine to show shortcuts in  windows  info but not showing popups . 
btw , it happend  in Key Promoter before  and i switch it to Key Promoter X
![45adu8 y4q wji61uh 9s](https://user-images.githubusercontent.com/7594289/34621088-be81a782-f282-11e7-9009-0ac3618f58d3.png)

Intellij 2017.2.1
Windows 10
here is the log ~
[idea.log](https://github.com/halirutan/IntelliJ-Key-Promoter/files/1607405/idea.log)

**Comment by halirutan** [comment]
Please make sure you have removed the old Key-Promoter. Then, you might want to look at this issue and see if it is the reason: https://github.com/halirutan/IntelliJ-Key-Promoter-X/issues/13

Btw, please note that the Key Promoter X has its own repository since the code base is not the same.

**Comment by zach007** [comment]
yes! problem sovled ! it's showing the popups~ thank you very much^_^ , the same issus [https://github.com/halirutan/IntelliJ-Key-Promoter-X/issues/13](url)
