### ISSUE TITLE
Request: Allow adding actions to ignore list

### ISSUE THREAD

**Issue by Dgc2002** [halirutan/IntelliJ-Key-Promoter#3]
One thing that I can see getting on my nerves is having a notification pop up every time I perform an action with the mouse. There are just some actions that I don't need or want a shortcut for. For example I won't be opening the tool window shortcut for this plugin often enough to need a key combination assigned to it, but now every time I click it a suggestion pops up to create one.  
  
I would love if I could configure this plugin to ignore the action that prompted the notification.

**Comment by halirutan** [comment]
This is an extremely nice idea! I'm sure I can implement such a "black list" and make it available in the "Key Promoter X" tool-window.

**Comment by halirutan** [comment]
Implemented in https://github.com/halirutan/IntelliJ-Key-Promoter/releases/tag/v5.3
