### ISSUE TITLE
Wrong Shortcuts are displayed

### ISSUE THREAD

**Issue by pheanex** [halirutan/IntelliJ-Key-Promoter#5]
The plugin shows wrong/non-existant shortcuts/suggestions. See screenshot
![img](https://i.imgur.com/seiyYMR.png)
Does it maybe not recognize custom key-shortcuts?

**Comment by halirutan** [comment]
I see. I'm sure I know what happens and I think I can fix this. The output is not entirely incorrect because *you did* press on the menu bar for rename and its shortcut is `Alt+R` but I see that it is much preferable to get the shortcut of the action invoked. Thanks for the report

**Comment by pheanex** [comment]
Thank you for your quick reply/review. I really appreciate your work.
If you need anything else for debugging (logs, etc) I'd be glad to provide it.

**Comment by halirutan** [comment]
@pheanex I'm not sure, but for me the correct shortcut is displayed. I see you are on Linux. What I don't see in your screenshot is the "Supressed tips" list that should be below the statistics. Can you specify the exact IDEA version you are using (and if it is Ultimate or Community).

The current version of the KeyPromoter X is 5.3 which is available for IDEA 162-171.*

I assume you use a newer 172 version? Then I can simply fix the version required for the plugin.

**Comment by pheanex** [comment]
Output of "About":

> IntelliJ IDEA 2017.2 EAP
> Build #IU-172.3317.6, built on July 4, 2017
> IntelliJ IDEA EAP User
> Expiration date: August 3, 2017
> JRE: 1.8.0_152-release-915-b3 amd64
> JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
> Linux 4.9.0-1-amd64

It's the Ultimate Edition.
As far as i can see from the Plugins settings, KeyPromoter is installed in version 5.1

I do not know how to get to the "Supressed tips"

**Comment by halirutan** [comment]
@pheanex You should receive an update notification for version 5.4 soon. You can update manually going to Settings -> Plugins -> Keypromoter X. Then right-click on the entry and "update". Before you update might be a good idea to delete your statistics data.

**Comment by pheanex** [comment]
@halirutan thank you for the update. Currently manual update is not possible (update button greyed out), but i guess it will take some time => i'm happily waiting for the update.
Thank you 😃

**Comment by halirutan** [comment]
@pheanex Please report back when it worked, because I already see the update. You can download the latest version here

https://plugins.jetbrains.com/plugin/9792-key-promoter-x

and choose install from disk. Not, that I overlooked something, but as far as I can see, the problem was your EAP version that has a version number > 171.*.

**Comment by pheanex** [comment]
Ok, i was able to update the plugin now (I had to reload the plugin list, to see the available update).
Unfortunately though, now for the refactor/rename example, the promoter plugin does not show any hints.
It is generally still working (Other things like "Build Project" still work).
As far as i can see there are no exceptions in the idea.log

**Comment by halirutan** [comment]
What have you chosen in Settings -> Tools -> Key Promoter?

![screen shot 2017-07-10 at 14 49 21](https://user-images.githubusercontent.com/511683/28018883-35c5d534-657f-11e7-855c-bf2ab6d420d4.png)

With "Menus Actions" enabled it should work.

**Comment by pheanex** [comment]
Ah, yes that was the missing piece.
With that option enabled, it also shows me the hint for refactor/rename. Very cool.
I guess enabling this option as default is another feature ;-)
But this issue is solved perfectly now ;-) Thank you

**Comment by halirutan** [comment]
Yes, I'll turn all options on in the next release. Btw, we do have a [Gitter Room](https://gitter.im/IntelliJ-Key-Promoter-X/Lobby).
