### ISSUE TITLE
Suggestions appear when a key mapping is used

### ISSUE THREAD

**Issue by Dgc2002** [halirutan/IntelliJ-Key-Promoter#6]
Key Promoter displays suggestions to create shortcuts for the following commands when a key mapping was used to invoke the action.  
  
Command: Back & Forward
I have mouse buttons(the ones usually used to go 'back' and 'forward' in browsers/file explorers) mapped to the back and forward commands.  
  
Command: Declaration  
One of the key mappings I use for 'declaration', or go to declaration, is 'Ctrl+Button1 Click'. I've even added this to the ignore list and it still appears.  
Adding this command to the ignore list didn't stop future suggestions, even though it was visible on in the ignore list.  
Another issue related to this is that when I used the middle mouse button, which at the time was also bound to Declaration, to dismiss the notification it would re-trigger the suggestion.

**Comment by halirutan** [comment]
Thanks for the report. There was indeed a bug in the code, where I suppressed tips only for certain items. In the original Key Promoter code, we used the pure AWT mouse click to find out where you clicked, if it was a button, if the button had a shortcut, and so on. This was very unreliable in many situations. By pure accident I stumbled over the `com.intellij.openapi.actionSystem.ex.AnActionListener` interface that lets us track many many more things. E.g. the `Ctrl+Click` for *go to declaration* or menu items on MacOS.

I missed extending the testing if an item is suppress for all things that came from this `AnActionListener`. This is fixed now and you should be able to suppress all tooltips you like.

About your other issues: Unfortunately, I cannot easily infer if you have manually set a mouse shortcut (and predict if that means that you don't want to see the tooltip for the shortkeys again). I guess it would be possible to compare the default keymap with the current one or add an `addShortcutChangeListener`. Both methods seem rather unreliable and might clash with other users expectations.

Please just suppress the mouse actions that you don't want a tip for. It should work now and the new **version 5.5** will be online in a few moments.
